{
 "title": "Redis Dashboard for Prometheus Redis Exporter",
 "description": "Redis Dashboard for Prometheus Redis Exporter",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "app",
    "query": "label_values(redis_instance_info, kubernetes_name)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(redis_up{kubernetes_name=\"$app\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "description": "redis status",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_up{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Redis Version",
   "type": "singlestat",
   "description": "redis version",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "redis_instance_info{instance=\"$instance\"}",
     "legendFormat": "{{ redis_version }}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{instance=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "singlestat",
   "description": "connected clients",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_connected_clients{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Blocked Clients",
   "type": "singlestat",
   "description": "Blocked clients",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_blocked_clients{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (redis_memory_used_bytes{instance=~\"$instance\"}  / redis_memory_max_bytes{instance=~\"$instance\"} )"
    }
   ]
  },
  {
   "title": "Connections Utilisation",
   "type": "graph",
   "description": "connections Utilisation",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "redis_connected_clients{instance=~\"$instance\"} / redis_config_maxclients{instance=\"$instance\"}",
     "legendFormat": "{{ Utilisation }}"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "qps"
    }
   ]
  },
  {
   "title": "Memory Usage Percent",
   "type": "graph",
   "description": "Memory Usage Percent",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (redis_memory_used_bytes{instance=~\"$instance\"}  / redis_memory_max_bytes{instance=~\"$instance\"} )",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "CPU Usage Percent",
   "type": "graph",
   "description": "CPU Usage Percent",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (rate (redis_cpu_sys_seconds_total{instance=\"$instance\"}[5m]) + rate (redis_cpu_user_seconds_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "Cpu Usage"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=~\"$instance\"} ",
     "legendFormat": "used"
    },
    {
     "expr": "redis_memory_max_bytes{instance=~\"$instance\"} ",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ input }}"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ output }}"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=~\"$instance\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  {
   "title": "Expires vs Not-Expires Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=~\"$instance\"}) - sum (redis_db_keys_expiring{instance=~\"$instance\"}) ",
     "legendFormat": "not expires"
    },
    {
     "expr": "sum (redis_db_keys_expiring{instance=~\"$instance\"}) ",
     "legendFormat": "expires"
    }
   ]
  },
  {
   "title": "Expired / Evicted Per Seconds",
   "type": "graph",
   "description": "每秒过期或驱逐的 key 的数量",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_expired_keys_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "expired /s"
    },
    {
     "expr": "rate(redis_evicted_keys_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "evicted /s"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{instance=\"$instance\"} [1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  }
 ]
}