apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-scheduler
  name: kube-scheduler
  namespace: kube-system
spec:
  type: ClusterIP
  clusterIP: None
  #selector:
  #  k8s-app: kube-scheduler
  ports:
  - name: https-metrics
    port: 10259
    protocol: TCP
    targetPort: 10259
