apiVersion: v1
data:
  password: <YOUR-REDIS-PASSWORD-BASE64>
kind: Secret
metadata:
  name: redis-exporter-prometheus
  namespace: monitoring
type: Opaque
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: monitoring
  name: redis-exporter-prometheus
spec:
  replicas: 1
  template:
    metadata:
      name: redis-exporter-prometheus
      labels:
        app: redis-exporter-prometheus
    spec:
      containers:
      - name: redis-exporter-livesone-app
        image: oliver006/redis_exporter:latest
        resources:
          requests:
            cpu: "20m"
            memory: "100Mi"
          limits:
            cpu: "50m"
            memory: "200Mi"
        ports:
        - containerPort: 9121
          protocol: TCP
        env:
        - name: REDIS_ADDR
          value: <YOUR-REDIS-ADDRESS:PORT>
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-exporter-prometheus
              key: password
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: redis-exporter-prometheus
  labels:
    app: redis-exporter-prometheus
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
spec:
  ports:
  - port: 9121
    targetPort: 9121
    protocol: TCP
  selector:
    app: redis-exporter-prometheus
