apiVersion: apps/v1
kind: Deployment
metadata:
  name: dingtalk-webhook
  namespace: monitoring
  labels:
    app: dingtalk-webhook
spec:
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: dingtalk-webhook
  template:
    metadata:
      labels:
        app: dingtalk-webhook
    spec:
      containers:
      - name: dingtalk-webhook
        image: timonwong/prometheus-webhook-dingtalk:v1.4.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "50m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "300Mi"
        args:
        - --ding.profile=webhook1=https://oapi.dingtalk.com/robot/send?access_token=<YOUR-ACCESS-TOKEN>
        ports:
        - name: dingtalk
          protocol: TCP
          containerPort: 8060

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dingtalk-webhook
  name: dingtalk-webhook
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
  - port: 8060
    protocol: TCP
    targetPort: dingtalk
  selector:
    app: dingtalk-webhook
