apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elastic-cerebro
  name: cerebro
  namespace: elastic-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-cerebro
  template:
    metadata:
      labels:
        app: elastic-cerebro
    spec:
      enableServiceLinks: false
      containers:
      - image: lmenezes/cerebro:0.9.1
        name: elastic-cerebro
        args:
        - -Dhosts.0.host=http://elasticsearch:9200
        ports:
        - containerPort: 9000
          name: cerebro
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elastic-cerebro
  name: elastic-cerebro
  namespace: elastic-system
spec:
  type: ClusterIP
  ports:
  - name: cerebro
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: elastic-cerebro

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: elastic-cerebro
  name: aelastic-cerebro
  namespace: elastic-system
spec:
  rules:
  - host: cerebro.fdisk.cc
    http:
      paths:
      - backend:
          serviceName: elastic-cerebro
          servicePort: cerebro
        path: /
  tls:
  - hosts:
    - cerebro.fdisk.cc
    secretName: cerebro.fdisk.cc
