apiVersion: v1
kind: Endpoints
metadata:
  name: kube-controller-manager
  namespace: kube-system
  labels:
    k8s-app: kube-controller-manager
subsets:
  - addresses:
    - ip: 10.0.100.3
    - ip: 10.0.100.4
    - ip: 10.0.100.5
    ports:
      - name: https-metrics
        port: 10257
        protocol: TCP
