apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: cerebro
    env: prod
  name: cerebro
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cerebro
      env: prod
  template:
    metadata:
      labels:
        app: cerebro
        env: prod
    spec:
      enableServiceLinks: false
      containers:
      - image: lmenezes/cerebro:0.9.1
        name: cerebro
        args:
        - -Dhosts.0.host=http://172.16.255.4:9200
        ports:
        - containerPort: 9000
          name: cerebro
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cerebro
    env: prod
  name: cerebro
  namespace: kube-system
spec:
  type: ClusterIP
  ports:
  - name: cerebro
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: cerebro
    env: prod

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: |
      39.106.82.47,101.201.142.55,
      203.100.83.41,203.100.83.42,
      172.16.0.0/12
  labels:
    app: cerebro
    env: prod
  name: cerebro
  namespace: kube-system
spec:
  rules:
  - host: cerebro.fdisk.cc
    http:
      paths:
      - backend:
          serviceName: cerebro
          servicePort: 9000
        path: /
  tls:
  - hosts:
    - cerebro.fdisk.cc
    secretName: cerebro.fdisk.cc
