apiVersion: v1
kind: Service
metadata:
  name: traefik-kubernetes-ingress
  namespace: traefik-ingress
spec:
  type: NodePort
  selector:
    k8s-app: traefik-ingress
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
    - name: https
      port: 443
      targetPort: https
      nodePort: 30443