apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-lb
  namespace: kube-system
spec:
  type: NodePort
  selector:
    k8s-app: traefik-ingress
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80
      nodePort: 30080
    - protocol: TCP
      port: 443
      name: https
      targetPort: 443
      nodePort: 30443
