apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-lb
  namespace: kube-system
spec:
  type: LoadBalancer
  selector:
    k8s-app: traefik-ingress
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80
    - protocol: TCP
      port: 443
      name: http
      targetPort: 443
