kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  tls:
  - hosts:
    - k8s-alertmanager.fdisk.cc
    secretName: wildcard.fdisk.cc
  rules:
  - host: k8s-alertmanager.fdisk.cc
    http:
      paths:
      - path: /
        backend:
          serviceName: alertmanager-main
          servicePort: 9093
