apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devops-tools-pvc
  namespace: default
spec:
  storageClassName: "nfs-storageclass"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi