apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: traefik-ingress
  name: traefik-ingress
  namespace: monitoring
spec:
  endpoints:
  - port: admin
    interval: 30s
    path: /metrics
    scheme: http
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: traefik-ingress-dashboard
